Feat/#106 챌린지 상세지도 화면 구현
dnd-side-project/dnd-7th-1-iOS pull request #113
Opened 2023-02-09 08:46 UTC by iowa329

## PR 요약
챌린지 상세지도 화면 구현
- Navigation Push를 위한 챌린지 진행중/완료 ViewContoller 구조 리팩토링(TableView -> baseScrollView)
- mapVC를 상속받아 ChallengeDetailMiniMap / ChallengeDetailMap VC 구현
- 색칠된 Friend Annotation 클래스 추가

## 변경 사항
- 색칠된 친구 마커(FriendColoredAnnotation) 추가를 위한 MapVC 내부 코드 수정

## TODO
- 상세지도 화면 API를 호출 할 때 자신의 경로(블록 좌표 목록)가 어떤건지 알 수 없는 구조 문제로 현재는 모두 동일한 친구마커로 화면이 구성되어있습니다. 추후 서버 리스펀스 코드 업데이트 이후에 반영할 예정입니다
- 현재 날아오는 데이터 값은 블록목록과 순위목록의 순서가 일치하지 않는 문제가 있어 추후 백엔드와 논의 후 수정 반영할 예정입니다

##  ScreenShot
<img width="300" alt="image" src="https://user-images.githubusercontent.com/26570294/217758321-164b15df-4003-4b91-b7fa-2e0532fa0fa7.png">

#### Linked Issue
close #106

2023-02-16 16:01 UTC, yunkyung-Hwang requested changes
- 디자인 수정 부분 반영 필요!
- 확실히 상속이나 재사용 구조는 같이 이야기를 하고 진행하는게 좋을 것 같네욤.. 기존 지도에서 기능을 더 쪼갤 부분도 보이고 상속이나 객체 생성 부분도 맞추면 관리하기 더 편해질 것 같아요 날 한 번 잡으시죠!

2023-02-20 05:28 UTC, iowa329 commented on NEMODU/NEMODU/Screen/ChallengeRanking/ViewController/Challenge/ChallengeDetail/ChallengeDetailMiniMapVC.swift
> +    var uuid: String?
저것 외에도 서버호출과 푸쉬할 VC 설정을 위해 bindBtn 함수를 override 해야하기도 하고, 돋보기 버튼이 private 설정이 되어있어서 바인딩을 할 수 없어 구현하기 위해서는 부모코드를 자잘하게 수정해야 하는 부분이 있어서 기존 코드를 건들지 않고 아예 새로 구현(bindButton으로 구현)하고자 했습니다. 상속하는 방향으로 코드를 구현하는게 나으려나요?

2023-02-20 05:29 UTC, iowa329 commented on NEMODU/NEMODU/Screen/ChallengeRanking/ViewController/Challenge/ChallengeDetail/ChallengeDetailMapVC.swift
> +}
넵 리뷰 반영해서 수정하도록 하겠습니다!

2023-03-21 13:33 UTC, yunkyung-Hwang requested changes
주석으로 해 두신 부분이나 회의때 이야기한 필요 없어진 파일들 삭제가 안된 것 같아요!
확인 부탁드립니다아

2023-04-06 15:15 UTC, iowa329 commented on NEMODU/NEMODU/Screen/Share/View/NavigationBar.swift
> -        self.title.font = font
앗 그렇네요! 확인하고 수정 반영하겠습니다

2023-04-06 16:19 UTC, yunkyung-Hwang commented on NEMODU/NEMODU/Screen/Share/View/NavigationBar.swift
> -        self.title.font = font
코드 삭제는 상의 후에 하면 좋을 것 같아여

2023-04-06 17:21 UTC, iowa329 commented on NEMODU/NEMODU/Screen/Share/View/NavigationBar.swift
> -        self.title.font = font
넵 앞으로는 먼저 상의하고 수정하겠습니다🙇‍♂️

2023-04-11 08:12 UTC, yunkyung-Hwang approved these changes

2023-04-11 11:51 UTC, merged