Refactor/#117 Request & Response값 변경 수정반영
dnd-side-project/dnd-7th-1-iOS pull request #129
Opened 2023-04-07 12:14 UTC by iowa329

## PR 요약
변경된 Request & Response값 대응
- 날짜 parsing방법 수정(Res값 변경: yyyy-MM-dd -> yyyy-MM-dd'T'HH:mm:ss)
- 네모두 응답 시간포맷(yyyy-MM-dd'T'HH:mm:ss) 관리 함수 String+extension에 추가
- 챌린지 타입, 색깔, 수락여부 상태 등 판별값 모두 대문자(upper-case)로 변경
- 챌린지 GREEN 색상 추가
- 랭킹목록 조회 방식 변경(POST -> GET), 파라미터명 변경(start -> started, end -> ended)
- 걸음수(Step) 랭킹 API 주소 변경(-> /matrix/rank/step)
- 챌린지 상세보기 요청 파라미터 값 추가(uuid -> nickname&uuid)
- 챌린지 생성 요청 파라미터 수정(upper-case)

기타 오류수정
- 랭킹목록 재사용 문제(셀 배경색 표기오류) 수정
- 챌린지 생성 조건 누락 수정(시작 날짜선택, 생성버튼 활성화 조건)
- 챌린지 생성 친구선택 표시 StackView 레이아웃 오류 수정
- D-day 표기 오류 수정
- 유저 프로필 이미지 예외 처리 개선

* 지도관련 PR 커밋이 남아있는데 지도PR이 메인브랜치에 머지되고 나면 풀 받아 최신커밋 반영 후 진행하겠습니다!

## 변경 사항
- 챌린지 관련 Enum타입 upper-case 변경

##  ScreenShot

#### Linked Issue
close `#117`

2023-04-11 10:06 UTC, yunkyung-Hwang reviewed
현재 브랜치가 상당히.. 꼬여있는 느낌입니다.
이전 브랜치에서 작업하던 부분이 꼭 필요한 경우가 아니면
작업하던 브랜치에서 새 브랜치를 생성하지 마시고 main에서 생성해주세요

지도에서 생성했던 불필요한 coloredAnnotation등이 현재 브랜치에 남아있습니다.
이렇게 추가적인 수정 과정이 필요할 수도 있고 무엇보다 확인하기가 너무 힘이듭니다..

2023-04-17 10:46 UTC, iowa329 commented on NEMODU/NEMODU/Global/Extension/UIString+.swift
> +    }
넵! 확정성 측면에서 좋을 것 같습니다
수정해서 반영하겠습니다

2023-04-21 14:37 UTC, yunkyung-Hwang requested changes

2023-04-21 14:37 UTC, yunkyung-Hwang commented on NEMODU/NEMODU/Global/Extension/Date+.swift
> +}
Date타입 자체의 extension이라 다른 부분에서도 많이 사용될 수 있으니까 String으로 포멧을 지정해서 반환하는 것보다는 Int형으로 반환하고 필요에 따라 String 포멧을 적용하면 범용성이 더 올라갈 수 있을 것 같아요!

2자리 날짜가 공통으로 필요하시면 Int형으로 선언하고 따로 formatter 메서드나 extension을 선언하는 것도 좋을 것 같아요!

2023-04-21 14:47 UTC, yunkyung-Hwang requested changes

2023-04-24 10:34 UTC, iowa329 commented on NEMODU/NEMODU/Global/Extension/Date+.swift
> +}
넵 알겠습니다! insertComma와 동일한 방식으로 Int+에 추가해서 작업하겠습니다

2023-04-24 10:39 UTC, iowa329 commented on NEMODU/NEMODU/Screen/ChallengeRanking/ViewController/Challenge/ChallengeTV/Cell/InvitedFriendsTVC.swift
> +                }
넵 then 사용대신 특정값만 할당해서 마지막에 설정하는 방식으로 변경하겠습니다
함수를 빼도 좋을 것 같은데 저 함수자체가 셀의 초기설정을 하는 함수라 함수 내부에서 또 다른 함수를 호출하기 보다 해당 함수 내부에서 코드를 처리하는게 나아보여서요!

2023-04-30 06:44 UTC, yunkyung-Hwang approved these changes

2023-04-30 06:51 UTC, merged