Feat/#130 이용약관 동의 & 권한설정 화면 구성
dnd-side-project/dnd-7th-1-iOS pull request #131
Opened 2023-04-09 16:22 UTC by iowa329

## PR 요약
이용약관 동의, 앱 권한설정 안내 화면을 구성하였습니다

## ⚠️ 문제점
화면 흐름상  각 3가지의 이용약관 동의 목록 대해 버튼을 누르면 웹페이지로 이동하도록 코드가 구성되었으나, 어떤 이유에서 인지 stackView 내부에 있는 button.rx.tap이 작동하지 않아 페이지가 로딩되지 않는 문제가 있습니다. 일반 버튼을 stackView에 집어넣고 눌렀을 때는 제대로 작동하는 것으로 보아 TermsConditionsDetailButton을 구성하는 과정에서 해당 버튼에 tap이 닿지 않은 문제로 보이는데 원인을 찾지 못했습니다. 혹시라도 보이는 문제점이 있거나 해결방안이 있으면 코멘트 부탁드립니다🙇‍♂️

** 알림PR이 머지되면 풀을 받아 현재PR 커밋을 최신화하겠습니다!

## 안내사항
위치 : Screen - Login - ViewController
이용약관 동의 - TermsConditionsAgreementVC
앱 권한설정 안내 - SetAuthorityVC

##  ScreenShot
<img width="300" alt="image" src="https://user-images.githubusercontent.com/26570294/230784018-e2510342-3b4f-468f-aa8a-5a4eaca97101.png" > <img width="300" alt="image" src="https://user-images.githubusercontent.com/26570294/230784022-d6f466a2-fbb0-4e37-956a-f1053493602a.png" >
<img width="300" alt="image" src="https://user-images.githubusercontent.com/26570294/230784026-bec5e67c-5625-4c93-bc80-728a453e3664.png" >

#### Linked Issue
close #130

2023-04-11 11:16 UTC, yunkyung-Hwang requested changes
이슈 관련 코멘트 달았습니당

갠적으로 서비스 동의 버튼의 높이가 18로 너무 작은 듯하여 HIG에 위배되는데 디자이너 언니들과 상의해보시면 좋을 것 같습니당

새로 추가하신 Camera, RightArrow Asset은 이미 존재하는데 새롭게 추가하신 이유가 있나요??

2023-04-11 11:16 UTC, yunkyung-Hwang commented on NEMODU/NEMODU/Screen/Login/View/TermsConditionsDetailButton.swift
> +        }
button에 stackView를 베이스로 넣어버리면 스택이라는 '뷰' 가 버튼을 덮어버립니다
버튼의 Responder를 호출해야하는데 스택뷰로 덮여서 스택뷰의 responder만 계속 호출하는 구조가 되어버립니당
stackView 선언 부분에
```swift
$0.isUserInteractionEnabled = false
```
요거로 stackView의 responder를 차단하면 해결됩니다

2023-04-11 11:16 UTC, yunkyung-Hwang commented on NEMODU/NEMODU/Screen/Login/ViewController/TermsConditionsAgreementVC.swift
> +                    }
then은 생성자 라이브러리로 알고있습니다
이벤트를 통해 값을 변경할때는 그에 맞는 메서드를 생성해서 호출하는 구조로 가면 좋을 것 같아요!

2023-04-17 10:54 UTC, iowa329 commented on NEMODU/NEMODU/Screen/Login/ViewController/SetAuthorityVC.swift
> +    }
넵! 앱 권한 설정 안내 창 이후에 작업할 내용을 여기 버튼에 바인딩해서 구현하면 될 것 같습니다
TODO 주석문을 추가해 놓겠습니다

2023-04-17 11:32 UTC, iowa329 commented on NEMODU/NEMODU/Screen/Login/ViewController/TermsConditionsAgreementVC.swift
> +                        let detailButton = subview as? TermsConditionsDetailButton
아 너무 좋습니다! 수정해서 반영하겠습니다

2023-04-17 11:37 UTC, iowa329 commented on NEMODU/NEMODU/Screen/Login/View/TermsConditionsDetailButton.swift
> +        }
앗! 검색했을 때 나왔던 방법인데 다른 스택뷰에다가 계속 시도했었나보네요😅 이제 정상적으로 버튼이 눌립니다
감사합니당

2023-04-21 14:24 UTC, iowa329 commented
> 이슈 관련 코멘트 달았습니당
> 
> 갠적으로 서비스 동의 버튼의 높이가 18로 너무 작은 듯하여 HIG에 위배되는데 디자이너 언니들과 상의해보시면 좋을 것 같습니당
> 
> 새로 추가하신 Camera, RightArrow Asset은 이미 존재하는데 새롭게 추가하신 이유가 있나요??

해당 파일들이 같은 이미지임을 확인했지만 내부에 배수로 커지는 이미지 Set 크기가 달라서 피그마에 나와있는대로 레이아웃을 적용하면 작게나오는 경우가 발생하는 것을 확인했습니다. 디자이너 분들께서 같은 디자인의 이미지 파일에 다른 imageSet을 설정할 것 같습니다

2023-04-30 06:45 UTC, yunkyung-Hwang approved these changes

2023-04-30 06:51 UTC, merged